### ISSUE TITLE
Tutorial Request

### ISSUE THREAD

**Issue by dougmacklin** [belohlavek/phaser-es6-boilerplate#11]
Thanks for creating this awesome boilerplate! I'm just starting out with Phaser and went through their [Making Your First Game](http://phaser.io/tutorials/making-your-first-phaser-game) walkthrough. For beginner purposes, they keep things simple and put everything in a [single JS file](https://github.com/photonstorm/phaser/blob/master/resources/tutorials/02%20Making%20your%20first%20game/part9.html). This makes sense for the tutorial but obviously gets messy pretty quickly. I'm wondering if someone could start out with this boilerplate and create the same game. If I could just see that code it would go a long way towards me being to able to take advantage of ES6 / classes with Phaser.

**Comment by bsparks** [comment]
Not entirely sure if this is what you mean, however, just copy the assets folder from the tutorial into the static folder. Then replace GameState.js with this: https://gist.github.com/bsparks/d35274c737a8730ba0f5

**Comment by belohlavek** [comment]
What would you prefer: a blog post or a github repo with an example game? Maybe both? 
In any case, I've been asked for tutorials several times already and I was wondering if it'd worth the time to set up a blog. 

Hoy many of you (people who follow this repo) would read the blog?
Which topics would you expect to be covered?

**Comment by dougmacklin** [comment]
Thanks @bsparks! I get that that's one way to do it, however I'm wondering if it would make sense to modularize it and if so how to do so. For example, creating classes for the platforms / stars / player, separating the game state functions into individual files, etc. Basically just breaking everything up into individual component files that are then imported into GameState.js or other subfiles.

@belohlavek Either would be great, I would read a blog or read a github wiki, or just view the finished code / file structure. I guess a wiki would make the most sense so that it's forever attached to the repo and easily accessible, but really any would work.

Thanks for the feedback guys!

**Comment by bsparks** [comment]
here's another https://gist.github.com/bsparks/f38cd10e595e308e4485 all the files except GameState.js go into the objects folder... at least this is one way to split it up that seems logical to me

**Comment by dougmacklin** [comment]
Thanks @bsparks this is incredibly helpful!
