### ISSUE TITLE
Integrating Unit testing with karma/ jasmine

### ISSUE THREAD

**Issue by karneaud** [belohlavek/phaser-es6-boilerplate#13]
Hey,

I'm trying to integrate ttd testing with karma but can't seem to get it to work. see [this stackflow](http://stackoverflow.com/questions/36439829/framework-browserify-error-enotdir-not-a-directory-stat) for more info

Can you give me some insights on this as I'm still learning ES6 conventions

**Comment by belohlavek** [comment]
I have no experience with karma/jasmine for testing, but I like the idea of adding some test examples to the boilerplate. Having said that, I can't help you with your specific problem, sorry :sweat_smile:
I'll leave this open for a couple of days in case someone else has something to say!

**Comment by karneaud** [comment]
It's ok figured it out. Thanks, I think you should delete this issue as it was unrelated.
