### ISSUE TITLE
Where do assets need to go?

### ISSUE THREAD

**Issue by wookoouk** [belohlavek/phaser-es6-boilerplate#14]
where is best to put assets (textures, maps, etc) /assets? /src/assets?
Thanks 👍

**Comment by wookoouk** [comment]
I did some tests and static/assets seemed best, thanks.

**Comment by belohlavek** [comment]
Yes, the static directory is the way to go.

**Comment by wookoouk** [comment]
thanks, btw, love this boiler plate, I owe you.
