### ISSUE TITLE
How to pass parameters to state constructor?

### ISSUE THREAD

**Issue by zhouhao27** [belohlavek/phaser-es6-boilerplate#18]
I'm wondering how to pass parameters to constructor of Phaser.State? Is there a document for es6? Thanks.

**Comment by belohlavek** [comment]
What are you trying to do? (Maybe share some code?)

Phaser.state doesn't take parameters http://phaser.io/docs/2.5.0/Phaser.State.html

**Comment by zhouhao27** [comment]
@belohlavek I know how to do it now. Just passing parameters through **state.start** and overrides **init** in the particular state.

Thanks.
