### ISSUE TITLE
FontAwesome support

### ISSUE THREAD

**Issue by fyyyyy** [belohlavek/phaser-es6-boilerplate#27]
http://fontawesome.io/icons/
FontAwesome has tons of universal and customizable icons for buttons, menus etc.
Setting this up via webpack is a bit tricky, it would be great if this lib had FontAwesome support.

https://gist.github.com/Turbo87/e8e941e68308d3b40ef6

**Comment by chakan** [comment]
You can do this with the Webfont loader that is included in this repo.

Use it like this:
`WebFont.load({
      custom: {
        families: ['FontAwesome'],
        urls: ['assets/css/font-awesome.min.css']
      },
      google: {
        families: ['Monoton']
      },
      active: this.fontsLoaded
    })`

Then by the text creation you can reference each icon by their code:
`game.add.text(0, 0, '\uf028', style)`

**Comment by fyyyyy** [comment]
Thanks :)
